#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanQuyen
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Travel")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTOUR(TOUR instance);
    partial void UpdateTOUR(TOUR instance);
    partial void DeleteTOUR(TOUR instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::PhanQuyen.Properties.Settings.Default.TravelConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TOUR> TOURs
		{
			get
			{
				return this.GetTable<TOUR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TOUR")]
	public partial class TOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATOUR;
		
		private string _MALOAI;
		
		private string _TENTOUR;
		
		private System.Nullable<int> _SONGAY;
		
		private System.Nullable<int> _SOCHO;
		
		private System.Data.Linq.Binary _HINH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATOURChanging(string value);
    partial void OnMATOURChanged();
    partial void OnMALOAIChanging(string value);
    partial void OnMALOAIChanged();
    partial void OnTENTOURChanging(string value);
    partial void OnTENTOURChanged();
    partial void OnSONGAYChanging(System.Nullable<int> value);
    partial void OnSONGAYChanged();
    partial void OnSOCHOChanging(System.Nullable<int> value);
    partial void OnSOCHOChanged();
    partial void OnHINHChanging(System.Data.Linq.Binary value);
    partial void OnHINHChanged();
    #endregion
		
		public TOUR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATOUR", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATOUR
		{
			get
			{
				return this._MATOUR;
			}
			set
			{
				if ((this._MATOUR != value))
				{
					this.OnMATOURChanging(value);
					this.SendPropertyChanging();
					this._MATOUR = value;
					this.SendPropertyChanged("MATOUR");
					this.OnMATOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTOUR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENTOUR
		{
			get
			{
				return this._TENTOUR;
			}
			set
			{
				if ((this._TENTOUR != value))
				{
					this.OnTENTOURChanging(value);
					this.SendPropertyChanging();
					this._TENTOUR = value;
					this.SendPropertyChanged("TENTOUR");
					this.OnTENTOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONGAY", DbType="Int")]
		public System.Nullable<int> SONGAY
		{
			get
			{
				return this._SONGAY;
			}
			set
			{
				if ((this._SONGAY != value))
				{
					this.OnSONGAYChanging(value);
					this.SendPropertyChanging();
					this._SONGAY = value;
					this.SendPropertyChanged("SONGAY");
					this.OnSONGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCHO", DbType="Int")]
		public System.Nullable<int> SOCHO
		{
			get
			{
				return this._SOCHO;
			}
			set
			{
				if ((this._SOCHO != value))
				{
					this.OnSOCHOChanging(value);
					this.SendPropertyChanging();
					this._SOCHO = value;
					this.SendPropertyChanged("SOCHO");
					this.OnSOCHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HINH
		{
			get
			{
				return this._HINH;
			}
			set
			{
				if ((this._HINH != value))
				{
					this.OnHINHChanging(value);
					this.SendPropertyChanging();
					this._HINH = value;
					this.SendPropertyChanged("HINH");
					this.OnHINHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
